---
# https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/
- apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://repo.mysql.com/apt/debian/ jessie mysql-5.6
    - deb http://repo.mysql.com/apt/debian/ jessie connector-python-2.0
    # - deb http://repo.mysql.com/apt/debian/ jessie mysql-apt-config
    # - deb http://repo.mysql.com/apt/debian/ jessie mysql-5.6
    # - deb http://repo.mysql.com/apt/debian/ jessie mysql-tools
    # - deb-src http://repo.mysql.com/apt/debian/ jessie mysql-5.6
# deb http://repo.mysql.com/apt/{debian|ubuntu}/ {jessie|wheezy|trusty|utopic|vivid} {mysql-5.6|mysql-5.7|workbench-6.2|utilities-1.4|connector-python-2.0}

- apt_key:
    keyserver: pgp.mit.edu
    id: 5072E1F5
    state: present

- name: Update and upgrade apt packages
  sudo: true
  apt:
    update_cache: yes

- name: Install Mysql community-server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-community-server
